title: dongw00 blog
email: albadw0428@gmail.com
description: Web, blockChain blog
author: dongw00
baseurl: '/'
url: 'http://dongw00.github.io'

# Social Profiles
# twitter_username:  dongw00
github_username: dongw00
facebook_username: dongwoo0428

# Build settings
markdown: kramdown
paginate: 10
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
