title: dongw00 blog
email: albadw0428@gmail.com
description: Web, blockChain blog
author: dongw00
baseurl: '/'
url: 'http://dongw00.github.io'

categories: [Cryptograpy]

# Social Profiles
# twitter_username:  dongw00
# stackoverflow_username: dongw00
github_username: dongw00
facebook_username: dongwoo0428
# linkedin_username: dongw00

# disqus
disqus: dongw00-1

permalink: /:title

# used to estimate reading time
wpm: 70

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
